version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - "3308:3308"
    expose:
      - "3308"
    healthcheck:
      test: "exit 0"
    networks:
      - "mynet"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3308
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=orders
      - WEB_SERVER_PORT=8080
      - GRPC_SERVER_PORT=8081
      - GRAPHQL_SERVER_PORT=8082
    networks:
      - "mynet"
    depends_on:
      mysql:
        condition: service_healthy

networks:
  mynet:
    driver: "bridge"