# version: '3.8'
# services:
#   # app:
#   #   build: .
#   #   environment:
#   #     - DB_HOST=mysql
#   #     - DB_PORT=3306
#   #     - MYSQL_USER=fullcycle
#   #     - MYSQL_ROOT_PASSWORD=123456789
#   #     - DB_DRIVER=mysql
#   #     - MYSQL_DATABASE=orders
#   #     - WEB_SERVER_PORT=8080
#   #     - GRPC_SERVER_PORT=8081
#   #     - GRAPHQL_SERVER_PORT=8082
#   #   networks:
#   #     - "mynet"
#   #   depends_on:
#   #     mysql:
#   #       condition: service_healthy

#   mysql:
#     image: mysql:9.0
#     container_name: my-mysql
#     environment:
#       - MYSQL_ROOT_PASSWORD=123456789
#       - MYSQL_USER=fullcycle
#       - MYSQL_PASSWORD=123456789
#       - MYSQL_DATABASE=orders
#       - MYSQL_ROOT_HOST='%' ## REMOVER
#     ports:
#       - '3306:3306'
#     expose:
#       - '3303'
#     # volumes:
#     #   - mysql-volume:/var/lib/mysql
#     networks:
#       - "mynet"
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       interval: 10s
#       timeout: 5s
#       retries: 3
# # volumes:
# #   mysql-volume:
# #     driver: local
# ## remover volumes
# networks:
#   mynet:
#     driver: "bridge"

version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  app:
    build: .
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - MYSQL_USER=fullcycle
      - MYSQL_ROOT_PASSWORD=123456789
      - DB_DRIVER=mysql
      - MYSQL_DATABASE=orders
      - WEB_SERVER_PORT=8080
      - GRPC_SERVER_PORT=8081
      - GRAPHQL_SERVER_PORT=8082
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '8080:8080'
      - '8081:8081'
      - '8082:8082'
