version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: orders
      MYSQL_USER: fullcycle
      MYSQL_PASSWORD: 123456789
    ports:
      - "3306:3306"
    expose:
      - "3306"

    networks:
      - "mynet"
    volumes:
      - ./mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=fullcycle
      - DB_PASSWORD=123456789
      - DB_NAME=orders
      - WEB_SERVER_PORT=8080
      - GRPC_SERVER_PORT=8081
      - GRAPHQL_SERVER_PORT=8082
    networks:
      - "mynet"
    depends_on:
      - mysql

networks:
  mynet:
    driver: "bridge"