version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
  app:
    build: .
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456789
      - DB_DRIVER=mysql
      - DB_NAME=orders
      - WEB_SERVER_PORT=8080
      - GRPC_SERVER_PORT=8081
      - GRAPHQL_SERVER_PORT=8082
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '8080:8080'
      - '8081:8081'
      - '8082:8082'

volumes:
  mysql_data:
