version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks: 
      - network1
    
  auction:
    container_name: auction
    build: 
      context: .
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB=auctions
      - BATCH_INSERT_INTERVAL=7m
      - MAX_BATCH_SIZE=1
      - AUCTION_INTERVAL=10m
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks: 
      - network1
      
networks:
  network1: