version: '3'

services:
  jaegar-all-in-one:
    image: jaegartracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250" 
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
    
  serviceA:
    container_name: serviceA
    build: path/to/serviceA
    environment:
      - TITLE=serviceA
      - CONTENT=serviceA
      - BACKGROUND_COLOR=blue
      - REQUEST_NAME_OTEL=serviceA
      - OTEL_SERVICE_NAME=serviceA
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - jaegar-all-in-one
      - prometheus
      - otel-collector

  serviceB:
    container_name: serviceB
    build: path/to/serviceB
    environment:
      - TITLE=serviceB
      - CONTENT=serviceB
      - BACKGROUND_COLOR=blue
      - REQUEST_NAME_OTEL=serviceB
      - OTEL_SERVICE_NAME=serviceB
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - jaegar-all-in-one
      - prometheus
      - otel-collector
