version: '3'

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    # volumes:
    #   - ./.docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
    
  service_a:
    container_name: servicea
    build: 
      context: .
      dockerfile: cmd/a/Dockerfile
    environment:
      - TITLE=serviceA
      - CONTENT=serviceA
      - BACKGROUND_COLOR=blue
      - REQUEST_NAME_OTEL=serviceA
      - OTEL_SERVICE_NAME=serviceA
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - otel-collector

  service_b:
    container_name: serviceb
    build: 
      context: .
      dockerfile: cmd/b/Dockerfile
    environment:
      - TITLE=service_b
      - CONTENT=service_b
      - BACKGROUND_COLOR=blue
      - REQUEST_NAME_OTEL=service_b
      - OTEL_SERVICE_NAME=service_b
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - otel-collector
