version: '3'

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    # volumes:
    #   - ./.docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
    
  service_a:
    container_name: servicea
    build: 
      context: .
      dockerfile: cmd/a/Dockerfile
    environment:
      - PORT_SERVICE_A=:9000
      - PORT_B=:8000
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:8889
      - SERVICE_NAME_A=service_a
      - SERVICE_NAME_B=service_b
      - SERVICE_B_URL=http://serviceb:8000/
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    ports:
      - "9000:9000"
    depends_on:
      - prometheus
      - otel-collector
      - zipkin

  service_b:
    container_name: serviceb
    build: 
      context: .
      dockerfile: cmd/b/Dockerfile
    environment:
    - PORT_SERVICE_A=:9000
    - PORT_B=:8000
    - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:8889
    - SERVICE_NAME_A=service_a
    - SERVICE_NAME_B=service_b
    - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
      - otel-collector
