package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/thalisonh/20-CleanArch/internal/infra/graph/model"
	"github.com/thalisonh/20-CleanArch/internal/usecase"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input *model.OrderInput) (*model.Order, error) {
	out, err := r.CreateOrderUseCase.Execute(usecase.OrderInputDTO{
		ID:    input.ID,
		Price: input.Price,
		Tax:   input.Tax,
	})
	if err != nil {
		return nil, err
	}

	return &model.Order{
		ID:         out.ID,
		Price:      out.Price,
		Tax:        out.Tax,
		FinalPrice: out.FinalPrice,
	}, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*model.Order, error) {
	list := []*model.Order{}
	orders, err := r.ListOrdersUseCase.Execute()
	if err != nil {
		return nil, err
	}

	for _, item := range orders {
		list = append(list, &model.Order{
			ID:         item.ID,
			Price:      item.Price,
			Tax:        item.Tax,
			FinalPrice: item.FinalPrice,
		})
	}

	return list, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
