version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks: 
      - network1
    
  limit:
    container_name: limit
    build: 
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks: 
      - network1
      
networks:
  network1: